### ISSUE TITLE
confusing language in readme: plural vs singular on has_many & belongs_to

### ISSUE THREAD

**Issue by joshuabamboo** [learn-co-curriculum/sinatra-activerecord-associations-join-tables#23]
The readme states: `The has_many :through is always singular and in the first part of the join table name, and the belongs_to portion of the relationship is pluralized in the second part of the table name.`

While it is trying to explain the way join tables are named (eg `user_items` -- `user` is singular and `items` is plural). It is confusing, and I've seen it mislead students to think that `has_many :through` should be singular and `belongs_to` should be plural.

@cernanb @ruthmesfun

**Comment by sgharms** [comment]
Hey @joshuabamboo I don't see the word `plural` appearing anywhere in this challenge. Maybe you have an old revision, but it's not present in `master`. Please reopen if we've missed something.

Thanks 💙

**Comment by joshuabamboo** [comment]
Looks like it was fixed by 80c2e74448e65ced0f3181a43b5dd334edd7b37c

Hm, I'm not sure where I saw it yesterday. I should've noted the track. If I see it again, I'll ping you. Sorry about that!
